FROM node:18-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npm run build

FROM node:18-alpine

RUN npm install -g serve

COPY --from=build /app/build /app/build

WORKDIR /app

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]